### ISSUE TITLE
'str' object has no attribute 'edit' & Bot Spam on Command Execution

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1868]
**Describe the bug**
When executing the /ping or /restart commands, the bot crashes with the following errors:

ERROR - 'str' object has no attribute 'edit'
app-1  | 2025-07-07 06:08:51,355 - bot - ERROR - Request timed out

After this, the bot hangs for a while, then continuously sends response messages in a loop. The only way to stop it is by forcibly restarting the container on the VPS using:

sudo docker compose down

NOTE: This behavior occurs mostly when I execute the command /jl. The issue occurs intermittently, not always, as the bot can work fine for days."

**Expected behavior**
/ping and /restart should respond cleanly without entering an infinite message loop.

**Actual Behavior:**

Error is raised: 'str' object has no attribute 'edit'

Additional error: Request timed out

Bot continues sending the same response messages indefinitely.

Requires manual container restart to stop the behavior.

**Screenshots**

![Error vps](https://github.com/user-attachments/assets/a69029f2-63f5-4c70-99c3-ec72d1e233db)

![telegram loop error](https://github.com/user-attachments/assets/dbc13ab4-602f-4a92-a607-364dbdc89dca)

**Comment by erickyun** [comment]
> U send restart once and bot starts looping?

Yes, I tried downloading something from Twitter using /jl.
After that, the bot hangs for a while, and when I use /ping or /restart, it goes into a loop.

**Comment by erickyun** [comment]
> > > U send restart once and bot starts looping?
> > 
> > 
> > Yes, only once.
> > I tried downloading something from Twitter using /jl. After that, the bot hangs for a while, and when I use /ping and /restart, it goes into a loop.
> > OS: Buyvm vps Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-182-generic x86_64)
> 
> Bro stop the bot and delete all other images. Very weird no loop in that function

Hi, thanks for your suggestion! I tried cleaning the Docker images as you recommended—hopefully that resolves the issue.

Just to give more context: I’ve modified the bot to work with qBittorrent 4.6.1 again because I was experiencing very slow download speeds (~2MB/s) on the latest qBittorrent versions, while 4.6.1 gives me around 100MB/s. I'm not sure if these changes could be related to the issue, but here are the specific commits I made:

1. https://github.com/erickyun/mltb-fork/commit/276065ab537653e14ba710906cadd65230ecd910
2. https://github.com/erickyun/mltb-fork/commit/bf630669e585b37ec735aaa64c192ad54761a31c
3. https://github.com/erickyun/mltb-fork/commit/012125c790e0529f48c7a04373f4c12a20c849b2
4. https://github.com/erickyun/mltb-fork/commit/503283aa272e51c0e5d632ab9a2cb2b1db3ee995
5. https://github.com/erickyun/mltb-fork/commit/43d3638e52237344835fd4641ac4e31144092188
6. https://github.com/erickyun/mltb-fork/commit/9bec8191fe83b3dee337fd5aa1cb5a50c0280436

**Comment by anasty17** [comment]
> > > > U send restart once and bot starts looping?
> > > 
> > > 
> > > Yes, only once.
> > > I tried downloading something from Twitter using /jl. After that, the bot hangs for a while, and when I use /ping and /restart, it goes into a loop.
> > > OS: Buyvm vps Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-182-generic x86_64)
> > 
> > 
> > Bro stop the bot and delete all other images. Very weird no loop in that function
> 
> Hi, thanks for your suggestion! I tried cleaning the Docker images as you recommended—hopefully that resolves the issue.
> 
> Just to give more context: I’ve modified the bot to work with qBittorrent 4.6.1 again because I was experiencing very slow download speeds (~2MB/s) on the latest qBittorrent versions, while 4.6.1 gives me around 100MB/s. I'm not sure if these changes could be related to the issue, but here are the specific commits I made:
> 
> 1. [erickyun@276065a](https://github.com/erickyun/mltb-fork/commit/276065ab537653e14ba710906cadd65230ecd910)
> 2. [erickyun@bf63066](https://github.com/erickyun/mltb-fork/commit/bf630669e585b37ec735aaa64c192ad54761a31c)
> 3. [erickyun@012125c](https://github.com/erickyun/mltb-fork/commit/012125c790e0529f48c7a04373f4c12a20c849b2)
> 4. [erickyun@503283a](https://github.com/erickyun/mltb-fork/commit/503283aa272e51c0e5d632ab9a2cb2b1db3ee995)
> 5. [erickyun@43d3638](https://github.com/erickyun/mltb-fork/commit/43d3638e52237344835fd4641ac4e31144092188)
> 6. [erickyun@9bec819](https://github.com/erickyun/mltb-fork/commit/9bec8191fe83b3dee337fd5aa1cb5a50c0280436)
> 
> To install qBittorrent 4.6.1, I used the following command:
> 
> ```
> /shell curl -L -o /bin/qbittorrent-nox https://github.com/userdocs/qbittorrent-nox-static/releases/download/release-4.6.1_v1.2.19/x86_64-qbittorrent-nox && chmod a+rx /bin/qbittorrent-nox
> ```
> 
> Let me know if anything here stands out or if you think these changes could be causing any issues.
> 
> Thanks again!

U could face some issues in qbittorrent but this totally not related to ur issue. If u can tell me how to produce the issue maybe i can know what's happening

**Comment by erickyun** [comment]
> > > > > U send restart once and bot starts looping?
> > > > 
> > > > 
> > > > Yes, only once.
> > > > I tried downloading something from Twitter using /jl. After that, the bot hangs for a while, and when I use /ping and /restart, it goes into a loop.
> > > > OS: Buyvm vps Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-182-generic x86_64)
> > > 
> > > 
> > > Bro stop the bot and delete all other images. Very weird no loop in that function
> > 
> > 
> > Hi, thanks for your suggestion! I tried cleaning the Docker images as you recommended—hopefully that resolves the issue.
> > Just to give more context: I’ve modified the bot to work with qBittorrent 4.6.1 again because I was experiencing very slow download speeds (~2MB/s) on the latest qBittorrent versions, while 4.6.1 gives me around 100MB/s. I'm not sure if these changes could be related to the issue, but here are the specific commits I made:
> > 
> > 1. [erickyun@276065a](https://github.com/erickyun/mltb-fork/commit/276065ab537653e14ba710906cadd65230ecd910)
> > 2. [erickyun@bf63066](https://github.com/erickyun/mltb-fork/commit/bf630669e585b37ec735aaa64c192ad54761a31c)
> > 3. [erickyun@012125c](https://github.com/erickyun/mltb-fork/commit/012125c790e0529f48c7a04373f4c12a20c849b2)
> > 4. [erickyun@503283a](https://github.com/erickyun/mltb-fork/commit/503283aa272e51c0e5d632ab9a2cb2b1db3ee995)
> > 5. [erickyun@43d3638](https://github.com/erickyun/mltb-fork/commit/43d3638e52237344835fd4641ac4e31144092188)
> > 6. [erickyun@9bec819](https://github.com/erickyun/mltb-fork/commit/9bec8191fe83b3dee337fd5aa1cb5a50c0280436)
> > 
> > To install qBittorrent 4.6.1, I used the following command:
> > ```
> > /shell curl -L -o /bin/qbittorrent-nox https://github.com/userdocs/qbittorrent-nox-static/releases/download/release-4.6.1_v1.2.19/x86_64-qbittorrent-nox && chmod a+rx /bin/qbittorrent-nox
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know if anything here stands out or if you think these changes could be causing any issues.
> > Thanks again!
> 
> U could face some issues in qbittorrent but this totally not related to ur issue. If u can tell me how to produce the issue maybe i can know what's happening

I only have RealDebrid and Twitter/X accounts logged in. When I try to leech a tweet using /jl, nothing happens — no response from the bot. Then I try /ping and /restart (only one message is sent for each), but still no reply. After 5–10 minutes, the JDownloader download shows up, and the bot starts responding — first with the /ping and /restart replies, but then it enters a loop, repeatedly sending multiple /ping and /restart messages. It seems like the bot is freezing, then suddenly unfreezing and spamming the queued responses.

**Comment by erickyun** [comment]
> > > > > > > U send restart once and bot starts looping?
> > > > > > 
> > > > > > 
> > > > > > Yes, only once.
> > > > > > I tried downloading something from Twitter using /jl. After that, the bot hangs for a while, and when I use /ping and /restart, it goes into a loop.
> > > > > > OS: Buyvm vps Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-182-generic x86_64)
> > > > > 
> > > > > 
> > > > > Bro stop the bot and delete all other images. Very weird no loop in that function
> > > > 
> > > > 
> > > > Hi, thanks for your suggestion! I tried cleaning the Docker images as you recommended—hopefully that resolves the issue.
> > > > Just to give more context: I’ve modified the bot to work with qBittorrent 4.6.1 again because I was experiencing very slow download speeds (~2MB/s) on the latest qBittorrent versions, while 4.6.1 gives me around 100MB/s. I'm not sure if these changes could be related to the issue, but here are the specific commits I made:
> > > > 
> > > > 1. [erickyun@276065a](https://github.com/erickyun/mltb-fork/commit/276065ab537653e14ba710906cadd65230ecd910)
> > > > 2. [erickyun@bf63066](https://github.com/erickyun/mltb-fork/commit/bf630669e585b37ec735aaa64c192ad54761a31c)
> > > > 3. [erickyun@012125c](https://github.com/erickyun/mltb-fork/commit/012125c790e0529f48c7a04373f4c12a20c849b2)
> > > > 4. [erickyun@503283a](https://github.com/erickyun/mltb-fork/commit/503283aa272e51c0e5d632ab9a2cb2b1db3ee995)
> > > > 5. [erickyun@43d3638](https://github.com/erickyun/mltb-fork/commit/43d3638e52237344835fd4641ac4e31144092188)
> > > > 6. [erickyun@9bec819](https://github.com/erickyun/mltb-fork/commit/9bec8191fe83b3dee337fd5aa1cb5a50c0280436)
> > > > 
> > > > To install qBittorrent 4.6.1, I used the following command:
> > > > ```
> > > > /shell curl -L -o /bin/qbittorrent-nox https://github.com/userdocs/qbittorrent-nox-static/releases/download/release-4.6.1_v1.2.19/x86_64-qbittorrent-nox && chmod a+rx /bin/qbittorrent-nox
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Let me know if anything here stands out or if you think these changes could be causing any issues.
> > > > Thanks again!
> > > 
> > > 
> > > U could face some issues in qbittorrent but this totally not related to ur issue. If u can tell me how to produce the issue maybe i can know what's happening
> > 
> > 
> > I only have RealDebrid and Twitter/X accounts logged in with JDownloader. When I try to leech a tweet using `/jl`, nothing happens — no response from the bot. Then shortly I try `/ping` and `/restart` (only one message is sent for each), but still no reply. After 5–10 minutes, the JDownloader download shows up, and the bot starts responding — secondly with the `/ping` and `/restart` replies, but then it enters a loop, repeatedly sending multiple `/ping` and `/restart` messages. It seems like the bot is freezing, then suddenly unfreezing and spamming the queued responses.
> 
> Ram ? How much

2GB

**Comment by anasty17** [comment]
> > > > > > > > U send restart once and bot starts looping?
> > > > > > > 
> > > > > > > 
> > > > > > > Yes, only once.
> > > > > > > I tried downloading something from Twitter using /jl. After that, the bot hangs for a while, and when I use /ping and /restart, it goes into a loop.
> > > > > > > OS: Buyvm vps Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-182-generic x86_64)
> > > > > > 
> > > > > > 
> > > > > > Bro stop the bot and delete all other images. Very weird no loop in that function
> > > > > 
> > > > > 
> > > > > Hi, thanks for your suggestion! I tried cleaning the Docker images as you recommended—hopefully that resolves the issue.
> > > > > Just to give more context: I’ve modified the bot to work with qBittorrent 4.6.1 again because I was experiencing very slow download speeds (~2MB/s) on the latest qBittorrent versions, while 4.6.1 gives me around 100MB/s. I'm not sure if these changes could be related to the issue, but here are the specific commits I made:
> > > > > 
> > > > > 1. [erickyun@276065a](https://github.com/erickyun/mltb-fork/commit/276065ab537653e14ba710906cadd65230ecd910)
> > > > > 2. [erickyun@bf63066](https://github.com/erickyun/mltb-fork/commit/bf630669e585b37ec735aaa64c192ad54761a31c)
> > > > > 3. [erickyun@012125c](https://github.com/erickyun/mltb-fork/commit/012125c790e0529f48c7a04373f4c12a20c849b2)
> > > > > 4. [erickyun@503283a](https://github.com/erickyun/mltb-fork/commit/503283aa272e51c0e5d632ab9a2cb2b1db3ee995)
> > > > > 5. [erickyun@43d3638](https://github.com/erickyun/mltb-fork/commit/43d3638e52237344835fd4641ac4e31144092188)
> > > > > 6. [erickyun@9bec819](https://github.com/erickyun/mltb-fork/commit/9bec8191fe83b3dee337fd5aa1cb5a50c0280436)
> > > > > 
> > > > > To install qBittorrent 4.6.1, I used the following command:
> > > > > ```
> > > > > /shell curl -L -o /bin/qbittorrent-nox https://github.com/userdocs/qbittorrent-nox-static/releases/download/release-4.6.1_v1.2.19/x86_64-qbittorrent-nox && chmod a+rx /bin/qbittorrent-nox
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Let me know if anything here stands out or if you think these changes could be causing any issues.
> > > > > Thanks again!
> > > > 
> > > > 
> > > > U could face some issues in qbittorrent but this totally not related to ur issue. If u can tell me how to produce the issue maybe i can know what's happening
> > > 
> > > 
> > > I only have RealDebrid and Twitter/X accounts logged in with JDownloader. When I try to leech a tweet using `/jl`, nothing happens — no response from the bot. Then shortly I try `/ping` and `/restart` (only one message is sent for each), but still no reply. After 5–10 minutes, the JDownloader download shows up, and the bot starts responding — secondly with the `/ping` and `/restart` replies, but then it enters a loop, repeatedly sending multiple `/ping` and `/restart` messages. It seems like the bot is freezing, then suddenly unfreezing and spamming the queued responses.
> > 
> > 
> > Ram ? How much
> 
> 2GB

Watch the ram usage using htop and try to produce the issue. Jdownloader need more than this while downloading i guess
